<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HELLO WORLD</h1>
    <?php echo("Hello world")."<br>";
       echo"floor if 5.1 is".floor(5.1)."<br>";
       
       echo"ceil of 5.1 is".ceil(5.1)."<br>";
       echo"Today is :</b>".date("d/M/Y");
       echo"<br>";
      
      
      ?>
</body>
</html>